freqtrade/technical

- setup.py
> Change to install sub dirs under technical 

- technical/indicators.py
vfi and vfima now return same values as TV, or as near not to matter.
> Fixed breaking bug on sum VFI

- technical/util.py
I have replaced the resampling with a simple merge and ffill. Also added a interval shift, so that the close prices of the resampled df matches the original one. Not quite sure if this is right..
The resulting merged df looks like this (cf. issue #7 screenshots)
> working on fix for issue #7

- technical/indicators.py
- technical/tests/test_indicators.py
Added **very basic** ROI indicator starting at each buy == 1
> Add basic ROI indicator

- technical/indicators.py
Don't know why tests have succeeded. However, ...
> added missing numpy import

- technical/indicators.py
Added TD Sequential indicator with counter. Used the version from this post as a base.
https://hackernoon.com/how-to-buy-sell-cryptocurrency-with-number-indicator-td-sequential-5af46f0ebce1
> Added TD Sequential Indicator

- README.md
- technical/pivots_points.py
moved here from freqtrade-strategies
> pivots_points indicator added

- technical/indicators.py
the  ichimoku function did not use standard default parameters.
This also includes some optimizations by not copying the dataframe (and then selecting columns from these) - but building series as "standalone" variables before returning these.
While this does not solve the memory leak discovered in #69 (that's caused by pandas, not by this library) - it will still be a worthwile improvement.
> Align ichimoku to use standard default parameters

- technical/indicators.py
Add period argument in Williams Indicator to avoid inconsistent result based on data frame length.
> Williams indicator improvement

- technical/indicators.py
2 variables are not used , and are recalculated instead.
> fix unused variables

- README.md
- technical/indicators.py
- tests/test_indicators.py
- tests/test_util.py
This implementation would give performance boosts avoiding loop from pyti implementation with pure vectorized pandas calculations.
> Improve CMF

- technical/indicators.py
solving issue #81 , 
added a field for each future senkou span.
> add future data of senkou spans

- README.md
> Minor: Fix typos in README

- .github/workflows/ci.yml
- .gitignore
- requirements-dev.txt
- tests/exchange/test_exchange.py
Enable and run simple CI agiainst this repository.
Future enhancements will follow (like automatic release to pypi) - but i'd like to change a few things first - which will benefit from a running CI as we can be sure we did not break "everything" ...
> Add simple ci running tests

- README.md
- technical/indicators/indicators.py
Adds new indicators SSLChannels (Slack) and MADR (#92)
> New indicators

- technical/indicators/indicators.py
WMA which behaves identically to the WMA found in TV
> WMA from TV

- technical/consensus/consensus.py
Spelling, punctuation, and grammar corrections in comments.
Just trying to help improve the project(s) however I can :)
> Comment corrections

- technical/indicators/volatility.py
Choppiness index 
theory https://www.tradingview.com/scripts/choppinessindex/
slightly adapted from https://medium.com/codex/detecting-ranging-and-trending-markets-with-choppiness-index-in-python-1942e6450b58
this indicator is intended to helps in detecting a trending or ranging market.
values are the same as tradingview CHOP indicator.
> add Chopiness index

- technical/indicators/overlap_studies.py
Allow custom price for vwma like hl2 for RSI https://github.com/freqtrade/freqtrade-strategies/blob/main/user_data/strategies/hlhb.py#L95
> Enhance vwma overlap_studies.py

- technical/vendor/qtpylib/indicators.py
> Added support for numpy types

- technical/indicators/indicators.py
Don't fillna whole dataframe as part of indicator calculation
closes #395
> Don't fillna whole dataframe as part of indicator calculation

- technical/indicators/indicators.py
* Replace shift(+1) to shift()
* Fix the comments about MAs color
* Remove ma05_c because it's the same as leadMA
* Remove duplicate leadMA returned in the debug mode
> Trimming mmar

- .github/workflows/ci.yml
- pyproject.toml
- requirements.txt
Expecting windows CI to fail until https://github.com/freqtrade/freqtrade/pull/11646 is merged.
> chore: bump numpy and ta-lib
